const base = {
    // baseUrl: "http://39.106.37.28:5000",
    baseUrl: "http://127.0.0.1:5000",
    register: "/users/register",
    login: "/users/login",
    // selectOrder: "/orders/queryUser",
    selectOrder: "/Orders",
    adminLogin: "/administrators/login",
    selectRefund:"/Refunds",
    selectTheater:"/Theaters",
    deleteTheater:"/theaters",
    searchTheater:"/theaters",
    addTheater:"/theaters",
    editorTheator:"/theaters",
    refundOrder:"/refunds",
    commitRefund:"/refunds",
    selectTicket:"/Ticketprices",
    searchTicket:"/ticketprices",
    addTicket:"/ticketprices",
    deleteTicket:"/ticketprices",
    editorTicket:"/ticketprices",
    selectAdmin:"/Administrators",
    deleteAdmin:"/administrators",
    searchAdmin:"/administrators",
    addAdmin:"/administrators",
    editor:"/administrators",
}


export default base